all:
  children:
    zookeeper:
      hosts:
        zk1:
          ansible_host: 10.0.1.10
        zk2:
          ansible_host: 10.0.2.10
        zk3:
          ansible_host: 10.0.3.10
    solr_nodes:
      hosts:
        solr1:
          ansible_host: 10.0.1.20
        solr2:
          ansible_host: 10.0.2.20
        solr3:
          ansible_host: 10.0.3.20
